import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useState } from "react";
import {
  AiFillDashboard,
  AiFillDatabase,
  AiFillCaretDown,
} from "react-icons/ai";
import nookies from "nookies"

const Layout = ({ children, title, token }) => {

	const [dropdown, setDropdown] = useState(false)

  const router = useRouter()

  const handleLogout = async () => {
    // e.preventDefault()
    
    await axios.post("https://testcrud.fikrisabriansyah.my.id/api/logout", {} , {
      headers: {
        "Content-Type": "application/json",
        Authorization: "Bearer " + token,
      }
    })

    nookies.destroy(null, 'token')
    router.replace('/')
  }

  return (
    <>
      <div className="bg-slate-100">
        <Head>
          <title>{title}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen">
          <div className="w-1/5 bg-white flex flex-col gap-2">
            <div className="border-b p-6">
              <p className="uppercase font-semibold text-lg lg:text-xl xl:text-2xl">
                crud app
              </p>
            </div>
            <div className="flex flex-col gap-4 p-6">
              <Link href="/">
                <div className="flex items-center gap-2 bg-slate-100 p-2 rounded cursor-pointer">
                  <AiFillDashboard className="text-slate-600" />
                  <p className="font-medium text-slate-700">Dashboard</p>
                </div>
              </Link>
              <Link href="/product">
                <div className="flex items-center gap-2 bg-slate-100 p-2 rounded cursor-pointer">
                  <AiFillDatabase className="text-slate-600" />
                  <p className="font-medium text-slate-700">Product</p>
                </div>
              </Link>
            </div>
          </div>
          <div className="w-4/5 flex flex-col relative">
            <div className="p-6">
              <div className="flex justify-end bg-white py-4 rounded-xl">
                <div className="relative" onMouseEnter={() =>setDropdown(true)} onMouseLeave={() => setDropdown(false)}>
                  <div className="flex px-4 items-center gap-2 cursor-pointer">
                    <p className="text-sm font-semibold text-gray-600">
                      Username
                    </p>
                    <AiFillCaretDown className="text-gray-600" />
                  </div>
									<button type="button" className={ dropdown ? "bg-white rounded p-4 block absolute right-4 border top-5 hover:bg-gray-200" : "hidden"}>
										<p className="text-sm cursor-pointer" onClick={() => handleLogout()}>Logout</p>
									</button>
                </div>
              </div>
            </div>
            {children}
          </div>
        </main>
      </div>
    </>
  );
};

export default Layout;
